{{- if and .Values.ingress.enabled .Values.ingress.managedCertificateName }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Values.ingress.managedCertificateName }}
  labels:
    {{- include "cloudkite-frontend.labels" . | nindent 4 }}
spec:
  domains:
    - {{ .Values.ingress.host | quote }}
{{- end }}
