{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cloudkite-app.fullname" . }}
  labels:
    {{- include "cloudkite-app.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
    {{- if .Values.ingress.staticIpName }}
    {{ .Values.ingress.staticIpAnnotation }}: {{ .Values.ingress.staticIpName | quote }}
    {{- end }}
    {{- if .Values.ingress.forceHttps }}
    networking.gke.io/v1beta1.FrontendConfig: {{ include "cloudkite-app.fullname" . | quote }}
    {{- end }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          {{- range .Values.ingress.paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ default (include "cloudkite-app.fullname" $) .serviceName }}
                port:
                  number: {{ .servicePort | default $.Values.service.port }}
          {{- end }}
{{- end }}

