{{- if or .Values.secretProviderClass.enabled (and .Values.backend.enabled .Values.backend.databaseCredentials.enabled) }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ ternary .Values.backend.databaseCredentials.secretProviderClassName (.Values.secretProviderClass.name | default (include "cloudkite-app.fullname" .)) (and .Values.backend.enabled .Values.backend.databaseCredentials.enabled) }}
  labels:
    {{- include "cloudkite-app.labels" . | nindent 4 }}
spec:
  provider: {{ .Values.secretProviderClass.provider }}
  parameters:
    secrets: |
      {{- if and .Values.backend.enabled .Values.backend.databaseCredentials.enabled }}
      - resourceName: "projects/{{ .Values.backend.databaseCredentials.secretProject }}/secrets/{{ .Values.backend.databaseCredentials.secretId }}/versions/{{ .Values.backend.databaseCredentials.version }}"
        path: "{{ .Values.backend.databaseCredentials.fileName }}"
      {{- else }}
      {{- range .Values.secretProviderClass.secrets }}
      - resourceName: "{{ .resourceName }}"
        path: "{{ .path }}"
      {{- end }}
      {{- end }}
{{- end }}
