cloudkite-app:
  fullnameOverride: cloudkite-frontend

  image:
    repository: obachimex/cloudkite-frontend
    tag: fdb8525

  labels:
    app: cloudkite-frontend
    component: frontend

  env:
    - name: VITE_API_BASE_URL
      value: https://chimex.duckdns.org
    - name: VITE_APP_VERSION
      value: fdb8525
    - name: VITE_ENVIRONMENT
      value: production

  ingress:
    enabled: true
    className: gce
    host: chimex.duckdns.org
    annotations:
      acme.cert-manager.io/http01-edit-in-place: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    staticIpAnnotation: kubernetes.io/ingress.global-static-ip-name
    staticIpName: cloudkite-public-ingress-ip
    forceHttps: false
    tls:
      enabled: true
      secretName: chimex-duckdns-tls
    paths:
      - path: /auth
        pathType: Prefix
        serviceName: cloudkite-backend
        servicePort: 8000
      - path: /
        pathType: Prefix
        serviceName: cloudkite-frontend
        servicePort: 80

  certificate:
    enabled: false
    name: chimex-duckdns
    secretName: chimex-duckdns-tls
    annotations:
      cert-manager.io/issue-temporary-certificate: "true"
    issuerRef:
      name: letsencrypt-prod
      kind: ClusterIssuer

  autoscaling:
    enabled: true
