cloudkite-app:
  fullnameOverride: cloudkite-frontend

  image:
    repository: obachimex/cloudkite-frontend
    tag: df249aa

  labels:
    app: cloudkite-frontend
    component: frontend

  ingress:
    enabled: true
    className: gce
    host: chimex.duckdns.org
    staticIpAnnotation: kubernetes.io/ingress.global-static-ip-name
    staticIpName: cloudkite-public-ingress-ip
    forceHttps: false
    tls:
      enabled: true
      secretName: chimex-duckdns-tls
    paths:
      - path: /auth
        pathType: Prefix
        serviceName: cloudkite-backend
        servicePort: 8000
      - path: /
        pathType: Prefix
        serviceName: cloudkite-frontend
        servicePort: 80

  certificate:
    enabled: true
    name: chimex-duckdns
    secretName: chimex-duckdns-tls
    issuerRef:
      name: letsencrypt-prod
      kind: ClusterIssuer

  autoscaling:
    enabled: true
