apiVersion: v2
name: cloudkite-monitoring
description: Production monitoring stack for Cloudkite
type: application
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 61.9.0

